/* eslint-disable max-len */
import { Platform } from 'react-native';
import { getPhoneNumber } from 'react-native-device-info';

export const landingStrings = {
  createAccount: 'Create account',
  eula: 'EULA',
  helpAndContact: 'Help & Contact Us',
  privacyPolicy: 'Privacy Policy',
  seeAllGames: 'See all games',
  signIn: 'Sign in',
  termsAndConditions: 'Terms & Conditions',
  playFor: 'PLAY FOR',
  free: 'FREE',
  skipTutorial: 'Skip Tutorial',
  gotIt: 'Got It',
  finish: 'Finish'
};
export const deeplinkStrings = {
  referFriend:"refer_a_friend",
  iapSubscriptionPacks:'iap_subscription_packs',
  bonuses:'bonuses',
  iapTokenPacks:'iap_token_packs'
}
export const common = {
  loadMore: 'Load More'
};

export const createAccountStrings = {
  alreadyMember: 'Already a player?',
  and: 'and',
  chooseYourUsername: 'Choose your username...',
  continueWithGoogle: 'Continue with Google',
  completeAccount: 'Finish',
  continueWithApple: 'Continue with Apple',
  continueWithFacebook: 'Continue with Facebook',
  iAgreeTo: 'I agree to the',
  nameTaken: 'This name is already taken! Try something different.',
  nickNameTooLong: 'Nickname must be less than 13 characters'
};

export const signInStrings = {
  notUser: 'Not a user?',
  signInWithApple: 'Sign in with Apple',
  signInWithFacebook: 'Sign in with Facebook',
  signInWithGoogle: 'Sign in with Google'
};

export const gamePlayStrings = {
  buyTokens: 'Buy Tokens',
  errorMessage: "Looks like this game isn't active right now. Try one of our other games.",
  getReady: 'Get ready!',
  live: 'Live',
  playing: 'Playing',
  quickRefill: 'QUICK TOKENS',
  RefillString: 'Refill your tokens without\nlosing your spot in line!',
  purchaseDifferentPack: 'Want to purchase a different pack?',
  headToTokenStore: 'or head to the Token Store',
  lastWin: 'Last win'
};

export const gameRoomStrings = {
  backToGameRoom: 'Back to Game Room',
  backToChallenge: 'Back to Challenge',
  becomeVip: 'Become a VIP',
  free: 'FREE',
  gameRoom: 'Game Room',
  inUse: 'In use',
  lastWin: 'Last win:',
  logOut: 'Log Out',
  open: 'Open',
  orWin: 'or win',
  play: 'Play',
  tickets: 'tickets!',
  vip: 'VIP',
  SwipePrize: 'Swipe to select a category',
  bottomSearchPlaceHolder: 'Type Something...',
  watchLastWin: 'Watch Last Win',
  lastWinner: 'Last Winner',
  prize: 'Prize',
  prizes: 'Prizes',
  machines: 'Machines',
  howTo: 'How to',
  favoriteBanner: 'FAVORITES',
  myFavoritePrize: 'My Favorites',
  sharePrizeSubject: 'Play REAL claw machines and win REAL prizes on Winner Winner Live Arcade!',
  sharePrizeText:
    "I'm playing REAL claw machines and winning REAL prizes on Winner Winner Live Arcade! Join me and we'll both get free tokens!  [APP_INVITE_URL]",
  topPlayersOfWeek: 'Top players this week',
  ViewAll: 'View All',
  day:'a day',
  searchWinnerCircle:"Search Winner's Circle",
  enterPrizeName:"Enter Prize name",
  prizeTitle:`What prize would you \n like to see?`,
  successTitle:`Your prize request was\n submitted! Thank you`

};
export const liveHostedStrings = {
contestStartIn: 'Contest begins in',
winner: 'WINNERS!',
share: 'Share',
addComment: 'Add a Comment',
beginsIn: 'Begins in',
win: 'Win',
join: 'Join For',
watch: 'Watch', 
tickets: 'Tickets',
correct: 'Correct',
inCorrect: 'Incorrect',
goBack: 'Go Back',
enter: "Enter",
};

export const accountProfileStrings = {
  guest: 'Guest',
  awesome: 'Awesome!',
  changePhoto: 'Change Photo',
  emptyLeaderboardMessage: 'Keep playing while we update the leaderboard!',
  fillYourVault: 'Fill your vault by winning some prizes!',
  noPrizeVault: 'No prize available in prize vault.',
  freeTokensLevelUp: number => `Free ${number} tokens on level up`,
  history: 'History',
  lastUpdated: time => `Last updated: ${time} ago`,
  leaderboard: 'Leaderboard',
  maxLevelReached: 'Max level reached!',
  myPrizes: 'My Prizes',
  music: 'Music',
  freeTokensVipLevel: 'Free tokens on level up',
  TokenPurchasebonusVipLevel: 'Token Purchase % Bonus',
  TicketBonusVipLevel: 'Ticket Conversion Bonus',
  payment: 'Payment',
  pointsAwayFromLevel: (points, level) => `Only ${points} away from level ${level}`,
  prizeVault: 'Prize Vault',
  myWallet: 'MY WALLET',
  sfx: 'SFX',
  notification: 'Notifications',
  shipping: 'Shipping',
  subscriptions: 'Subscriptions',
  ticketConversionBonus: percent => `Ticket conversion ${percent}% bonus`,
  tokenPurchaseBonus: percent => `Token purchase ${percent}% bonus`,
  viewAll: 'View all',
  viewFullBoard: 'View full board',
  viewGames: 'View games',
  vip: 'VIP',
  weekly: 'Weekly',
  winnersCircle: "Winner's Circle",
  redeem: 'Redeem',
  cancel: 'Cancel',
  bonuses: 'Bonuses',
  achievement: 'Achievements',
  setting: 'Settings',
  share: 'Share',
  myInfo: 'My Info'
};

export const exploreArcade = {
  selectDifficulty: 'Select Difficulty',
  exploreArcade: 'Explore Arcade',
  allMachine: 'All Machines',
  allDifficulty: 'All Difficulty'
};

export const challenge = {
  collection: 'Collections',
  todayChallenge: "Today's Challenge",
  weeklyChallenge: 'Weekly Challenge',
  monthlyChallenge: 'Monthly Challenge',
  nochallengefound:"No challenge found"
};

export const challengeString = {
  description: 'The player with the most funko wins this week will win the grand prize.'
};

export const newsRoomStrings = {
  readMore: 'Read More',
  hide: 'Hide',
  news: 'News',
  latest: 'Latest',
  old: 'Old',
  expired: 'Expired',
  recentWins: 'Recent Wins'
};

export const gameResultScreenStrings = {
  betterLuckNextTime: 'Better luck next time!',
  inLine: 'in line',
  pickYourReward: 'Pick your reward:',
  playAgain: 'Play again',
  prizeWaitingInVault: 'Your prize will be waiting in your prize vault!',
  soClose: 'So close!',
  takePrizeAndFindNewGame: 'Take Prize',
  takeTicketsAndFindNewGame: 'Take Tickets',
  tryAgainForAnotherChance: 'Try again for another chance to win!',
  youDidntWinThisTime: "You didn't win... this time",
  tokenEndContent:"You need more tokens!\nHurry and refill now without\nlosing your spot in line"

};

export const bannerString = {
  turnOnNotifications: 'Turn on notifications',
  notificationBannerLineOne: 'Learn about new prizes,',
  notificationBannerLineTwo: 'token sales and more!',
  enable: 'enable'
};

export const popUpStrings = {
  tokenRefillDeal: 'TOKEN REFILL DEAL!',
  purchasePrompt: tokens =>
    `You're running low on tokens. Buy a quick refill pack right now and get ${tokens} FREE tokens!`,
  takeMeToGameRoom: 'Take me to Game Room',
  referringRewardOne: tokens => `You've earned ${tokens} free tokens!`,
  referringRewardTwo: 'Thank You for inviting friends',
  referringRewardThree: 'Be sure to thank your friend!',
  referringRewardFour: 'Want to earn more free tokens?',
  referringRewardFive: 'Start referring friends now!',
  referFriendsNow: 'Refer Friends Now!',
  referMoreFriends: 'Refer More Friends!',
  CONGRATS: 'CONGRATS!',
  referAFriend: 'REFER A FRIEND!',
  joinContest: 'JOIN!',
  joinContestTitle: 'Play for your chance at',
  joinContestTickets: 'TICKETS',
  eliminatedContestLine1: "YOU'RE",
  eliminatedContestLine2: 'ELIMINATED!',
  eliminatedTextLine1: 'Your answer was wrong! Come',
  eliminatedTextLine2: 'back again for your chance at',
  eliminatedTextLine3: 'huge prizes!',
  newLife: 'NEW LIFE?',
  newLifeTextLine1: 'Your answer was wrong. Hurry',
  newLifeTextLine2: 'and grab a new life if you think',
  newLifeTextLine3: `you've got what it takes to win.`,
  notificationLine1: 'TURN ON',
  notificationLine2: 'NOTIFICATION',
  notificationTextLine1: `Don't miss your chance at 100,000`,
  notificationTextLine2: 'tickets! Turn on notifications so',
  notificationTextLine3: 'you can be on time for all the fun.',
  turnOn: 'Turn On',
  noThankYou: 'No thank you',
  keepGoing: 'KEEP GOING?',
  keepGoingTextLine1: 'You can choose to walk away with',
  keepGoingTextLine2: '1,000 tickets or continue playing.',
  keepGoingTextLine3: 'What would you like to do?',
  keepPlaying: 'KEEP PLAYING',
  takeTickets: 'TAKE TICKETS',
  facebook: 'facebook',
  twitter: 'twitter',
  email: 'Email',
  more: 'More',
  sms: 'SMS',
  continueWatching: 'Continue Watching',
  youveEarnedTokens: "You've earned",
  lineOneDailyBonus: days => `Your login streak is ${days} ${days > 1 ? 'days.' : 'day.'} Come`,
  lineTwoDailyBonus: 'back tomorrow to extend your',
  lineThreeDailyBonus: 'streak and earn more tokens!',
  gotIt: 'Got it!',
  Buy: 'Buy',
  addTokensWithExclamationMark: 'Add Tokens!',
  backToGameRoom: 'Back',
  noThanksWithExclamationMark: 'No Thanks!',
  piggyBank: 'Piggy Bank',
  piggyBankYouHave: 'YOU HAVE',
  HeadingOnePiggyBankAddToken: tokens => `${tokens} TOKENS`,
  PiggyBankMoreToken: tokens => `${tokens} MORE TOKENS *`,
  lineOnePiggyBankAddToken: 'Unlock your piggy bank tokens at',
  lineTwoPiggyBankAddToken: 'anytime. Tokens are added every',
  lineThreePiggyBankAddToken: 'your bank is full and get an',
  lineFourPiggyBankAddToken: tokens => `additional ${tokens} tokens!`,
  lineFivePiggyBankAddToken: (tokens, tokensDisplay) =>
    tokens > 0 ? `Only ${tokensDisplay} tokens away from full!` : `Your bank is full!`,
  lineSixPiggyBankAddToken: 'time you play. The more you play',
  lineSevenPiggyBankAddToken: 'the better the savings!',
  lineOnePiggyBank: 'Unlock your Piggy Bank and receive',
  lineTwoPiggyBank: numberOfTokens => `${numberOfTokens}% tokens back for every play.`,
  Unlock: price => `Unlock for ${price}`,
  comparedText: price => `*When compare to standard token amount of ${price}.`,
  price: 'Price',
  noThankLowerCase: 'No thanks!',
  noThanks: 'No Thanks!',
  dealOfTheDayTextOne: token => `Get ${token} tokens right`,
  forOnly: 'for only ',
  thatsExtraText: "That's an extra ",
  dealOfTheDayTokenText: `tokens!`,
  dealOfTheDayFreeText: `FREE `,
  referFriendOne: 'For every friend you refer',
  referFriendScreenTitle: 'Refer friends and earn free tokens!',
  referFriendTwo: `who purchase a token pack,`,
  referFriendThree: "you'll get free tokens and",
  referFriendFour: `your friend will too!`,
  awesome: 'Awesome!',
  watchClaim: 'Watch And Claim',
  achievementUnlockedOne: points => `You unlocked an achievement and earned ${points} points.`,
  achievementUnlockedMultiple: points => `${points} points have been added to your account.`,
  rewardTxt: 'You have been rewarded',
  rewardTokenTxt: tokens => ` ${tokens}`,
  freeTokenTxt: ' free tokens.',
  // eslint-disable-next-line max-len
  claimedMessageTwo: (day, tokens) =>
    `Your login streak is ${day} ${day === 1 ? 'day' : 'days'}, and ${tokens} tokens have been added to your account.`,
  claimedMessageThree: `Come back tomorrow to receive more free tokens!`,
  claimedMessageOne: 'Congrats on earning your daily bonus!',
  claimsyourtokennow: 'Claim your tokens now!',
  dailyBonus: 'Daily Bonus!',
  freeTokenAward: tokens => `You have been awarded\n ${tokens} free tokens.`,
  stackEmReward: (tokens, games) => `You have earned ${tokens} Stack Em tokens for winning ${games} games!`,
  minPiggybank: minToken => `For unlock your Piggy Bank you should have minimum ${minToken} tokens in your account.`,
  newAccountBonus: 'Bonus',
  newAccountBonusMessage: 'Create an account today and',
  newAccountTokenBonusMessage: tokens => `Get ${tokens} FREE tokens!`,
  claim: 'Claim',
  notificationButtonText: 'Enable',
  enableNotifications: 'Enable Notifications',
  enableNotificationsMessage:
    'You will recieve our latest specials, personalized offer, new prize announcements, and so much more!',
  areYouSure: 'Are you sure?',
  mayBeLater: 'Maybe Later',
  backToMyPrizes: 'Back to my Prizes',
  becomeVip: 'Become A VIP',
  buyTokens: `Buy tokens`,
  buyTokensMessage: 'Buy any token pack to play any machine and get free shipping!',
  buyTokenToContinuePlay: 'Buy more tokens from the store to continue playing',
  cancel: 'Cancel',
  cancelAndKeepPrize: 'Cancel and keep prize',
  cancelAndSaveForLater: 'Cancel and save for later',
  createAccountToHoldYourPrizes:
    'Create an account to hold your prizes, collect tickets, earn stars, and keep playing!',
  chooseAnother: 'Choose another',
  congratulations: 'CONGRATS!',
  dontWantToShip: "I don't want to ship my prize yet",
  freeShipping: 'Free Shipping!',
  forTickets: 'for tickets?',
  gameNotActive: "Looks like this game isn't active right now.",
  machineNotActive: errorCode => `Something went wrong. Error code : ${errorCode}`,
  givingUp: 'Giving Up?',
  goBack: 'Go Back',
  getReadyForYourPrize: 'Get ready for your prize!',
  goToGameRoom: 'Go to Game Room',
  goToStore: 'Go to store',
  info: 'Info',
  useLater: 'USE  LATER',
  ok: 'OK',
  takeMeBack: 'Cancel',
  leaveAndRefund: "If you leave now we'll refund you, but you'll lose your spot in line.",
  leaveAndForfeit: "If you leave now you'll forfeit and lose your spot in line.",
  leavingSoSoon: 'Leaving so soon?',
  leaveInQueue: "If you leave now, you'll lose your spot in line.",
  locationError: 'LOCATION ERROR',
  locationCannotIdentified: 'Sorry, we cannot identify your current location which is required to meet regulations.',
  networkError: 'NETWORK ERROR',
  createAccount: 'CREATE ACCOUNT',
  // eslint-disable-next-line max-len
  networkErrorBody: `To keep playing, please check your internet connection and try again. \n\nAccess to Winner Winner may be restricted until your connection is established.`,
  noPlayHistory: 'No Play History',
  noPlayHistoryMessage: "You haven't played any games yet. Head to the Game Room to start playing!",
  outOfToken: 'Out of tokens',
  oops: 'OOPS!',
  oopsWithExclaimination: 'Oops!',
  pleaseContactSupport: 'Please contact support.',
  contactSupport: 'Contact Support',
  pleaseContactSupportForDetails: 'Please contact support for more details.',
  regionNotSupported: 'Sorry, your current region does not allow you to play these games.',
  networkErrorTextOne: 'To keep playing, please check your internet connection and try again.',
  networkErrorTextTwo: 'Access to Winner Winner may be restricted until your connection is established.',
  ship: 'Ship',
  shippingNotAvailableState: 'Shipping is not available\n in this state',
  shipNow: 'Ship now',
  success: 'SUCCESS!',
  swapForNumberTickets: number => `Swap for ${number} tickets`,
  swap: 'Swap',
  unavailable: 'Unavailable',
  unlockedAchievements: number => `You unlocked ${number} achievements!`,
  unsupportedRegion: 'UNSUPPORTED REGION',
  wow: 'wow',
  xPoints: points => `x${points}`,
  videoUnavailableText: 'Sorry, this video replay \nis unavailable.',
  viewAchievements: 'View achievements',
  viewTokenPacks: 'View token packs',
  yesLeave: 'Yes, leave',
  willGet: 'You Will',
  getText: 'Get',
  ticketsValueText: tickets => ` ${tickets} tickets`,
  plusText: ' plus',
  extraTicketText: extraTickets => ` ${extraTickets} extra tickets`,
  forVipLevel: ' for your VIP level',
  lineOnePurchasePrompt: `Looks like you're almost out of tokens,`,
  lineTwoPurchasePrompt: `but we've got you covered! Get`,
  lineThreePurchasePrompt: tokens => `${tokens} FREE TOKENS`,
  lineFourPurchasePrompt: `with a quick refill pack now!`,
  rewardedVideo: tokens => `Thanks for watching! ${tokens} tokens \n have been added to your \n account.`,
  adsUnavailable: 'Oops! Looks like there aren’t currently any ads to serve. Please check back again soon!',
  lineOneTracking: 'Ads help personalize your experience and keep games affordable.',
  lineTwoTracking: 'Improve your ads experience by opting into ad tracking to see ads that are most revelant to you.',
  HeadsUpText: `When you change your default country location, it will impact the prizes you see and their availability. Only prizes that are available in your selected country will be visible or redeemable. Please only change your default country setting temporarily if traveling.`,
  headsUp: 'HEADS UP!',
  confirmChanges: 'Confirm Changes',
  yourInfoHaveBeenUpdatedSuccessfully: 'Your information has been \n updated successfully.',
  backToProfile: 'Back to Profile',
  close: 'Close',
  forceUpdate: 'UPDATE REQUIRED',
  forceUpdateBody: `New version of Winner Winner is available and is required to continue, please click to update the latest version.`,
  forceUpdateBtn: 'UPDATE',
  avail: 'AVAIL',
  free: 'FREE',
  redemptionLimit: "The player's monthly redemption limit exceeded",
  watchAd_top: 'Watch this ad and get 5',
  watchAd_mid: 'tokens back before',
  watchAd_bottom: 'your play!',
  watchAdd_getToken: 'GET TOKENS',
  watchAd_freeToken: 'FREE TOKEN',
  watchAdd: 'WATCH AD',
  claimNft: 'CLAIM YOUR\n NFT!',
  claimNftBody: 'Enter an ethereum-based\n crypto wallet address to\n transfer your NFT.',
  continue: 'Continue',
  claimNftPlaceholder: 'Enter here...',
  confirmNft: 'CONFIRM!',
  confirmNftBody: 'Please review and confirm\n your crypto wallet address.',
  confirm: 'Confirm',
  transferredNft: 'TRANSFERRED!',
  transferredNftBody: 'Your NFT will be transferred\n to your ethereum wallet in the\n next 24 hours.',
  goBack: "Go Back to Game Room"
};

export const achievementsString = {
  achievements: 'Achievements',
  comeBack: 'Come back tomorrow!',
  earnedTimeStamp: date => `Earned ${date}`,
  oneMoreTicketNeeded: `1 more ticket needed!`,
  oneMoreWinNeeded: `1 more win needed!`,
  playAgain: 'Play again tomorrow!',
  ticketsNeeded: number => `${number} more tickets needed!`,
  winsNeeded: number => `${number} more wins needed!`,
  completed: 'Completed',
  inProgress: 'In Progress',
  allAchievements: 'All Achievements'
};

export const gameCardReloadStrings = {
  applied: 'applied!',
  bestValue: 'BEST VALUE',
  buyPrice: price => `Buy ${price}`,
  buyPriceToken: price => `${price}`,
  QuickPrice: price => `${price}`,
  buyTokenUnit: (token, unit) => `${token}${unit}`,
  code: 'Code',
  congratulations: 'Congratulations!',
  enterCouponCode: 'Enter your coupon code here...',
  inValidCode: 'Invalid code. Please try another.',
  isAlreadyApplied: 'is already applied',
  monthlyDiscount: 'Monthly token deposit at a great discount.',
  monthlyTokens: 'Monthly Tokens',
  packs: 'Tokens',
  TokenPacks: 'Token Store',
  bonuses: 'Bonuses',
  popular: 'POPULAR',
  dailyBonus: 'Daily Bonus',
  referAFreind: 'REFER A FRIEND',
  freePlay: 'FREE PLAYS',
  freePlayDetail_1: `To collect your free play,${'\n'} watch & claim`,
  freePlayDetail_2: `Come back${'\n'} soon!`,
  piggyBank: 'PIGGY BANK',
  stackEm: "STACK 'EM",
  winGameToday: games => `WIN ${games} GAMES TODAY`,
  playGameWeekly: games => `PLAY ${games} GAMES THIS WEEK`,
  rewardedVideo: 'WATCH AND EARN',
  rewardedVideoDetail: 'Earn free tokens by watching a quick ad.',
  rewardedVideoBtnText: 'Earn',
  inviteAFriendDetail: `Invite your friends.They will receive 10% bonus tokens and you'll get 500 free.`,
  piggyBankDetail: 'Unlock your Piggy Bank now!',
  claim: 'Claim',
  invite: 'Invite',
  stackEmDetail: (maxGames, token) => `Win ${maxGames} games and get ${token} tokens.`,
  todayBonusDetail: (maxGames, token) => `Win ${maxGames} games today and recieve ${token} bonus tokens!`,
  weekBonusDetail: (maxGames, token) => `Play ${maxGames} games this week and recieve ${token} bonus tokens!`,
  vipBonus: percentage => `VIP Bonus: ${percentage}%`,
  restorePurchases: 'Restore purchases',
  restoreSuccessful: 'Restore Successful',
  restoreSuccessfulMessage: 'You successfully restored your purchases',
  sale: 'Sale!',
  subscriptionPack: 'Subscription Pack',
  subscriptionBonus: percentage =>
    // eslint-disable-next-line max-len
    `All subscriptions include a ${percentage}% token purchase bonus, where you get additional tokens on purchasing any token pack.`,
  subscriptionIncludes: 'Every subscription includes:',
  subscriptions: 'Subscriptions',
  subscriptionTerms:
    // eslint-disable-next-line max-len
    `Payment will be charged to your ${
      Platform.OS === 'android' ? `Google Play` : `Apple ID`
    } account at the confirmation of purchase. Subscription automatically renews unless it is cancelled at least 24 hours before the end of the current period.`,
  tokenStore: 'token store',
  tokensToday: 'Tokens Today',
  tokenPurchaseBonus: (amount, bonusAmount) => `If you buy ${amount} tokens you will get ${bonusAmount} tokens.`,
  unitTokens: unit => `${unit} tokens`,
  unitTokenTotal: unit => `${unit} token total:`,
  vipStatus: 'VIP status includes free shipping and access to VIP exclusive games!',
  youAreVIPAnnouncement: "You're a VIP! You'll now get free shipping and access to VIP games!",
  BaseToken: 'Base Tokens',
  BonusToken: 'Your Bonus',
  BonusText: amount => `${amount} Tokens`,
  BonusTokenText: amount => `${amount}`,
  TotalToken: 'Total:',
  offerwall: 'COMPLETE AN ACTION & EARN',
  offerwallDetail: 'Earn free tokens by completing an action.',
  close: 'Close',
  wantMoreTickets: 'Want even more tokens?',
  learnMore: 'Learn More',
  claimAndWatch: reward => `You've been granted ${reward}. Watch this quick ad to claim them!`,
};

export const userInfoStrings = {
  username: 'Username',
  birthday: 'Birthday',
  myCountry: 'My Country',
  defaultShippingAddress: 'Default Shipping Address',
  myInfo: 'MY INFO',
  edit: 'Edit',
  save: 'Save',
  chooseYourfavoritePrize: 'Choose your 3 favorite prize categories',
  backToProfile: 'Back to profile'
};

export const winnersCircleStrings = {
  timesOne: 'x1',
  timesNumber: number => `x${number}`,
  popular: 'Popular',
  redeem: 'Redeem',
  redeemFor: 'Redeem for',
  redeemForTickets: (title, value) => `Redeem ${title} for ${value} tickets?`,
  close:'Close',
  deal:'Deal of the Day',
  endsIn:'Ends in ',
  digitalGameText:'Win more tickets \nplaying ',
  ticketAmountText :'Ticket Amount',
  sortByText: 'Sort By',
  showPrizes:'Show Prizes',
  filters:'Filters',
  requestprize:'Request a Prize',
};

export const prizeVaultStrings = {
  allPrizes: 'All prizes',
  new: 'New',
  Available: 'Available',
  packed: 'Packed',
  packingUp: 'Packing up',
  pending: 'Pending',
  shipped: 'Shipped',
  shipNow: 'Ship now',
  swapped: 'Swapped',
  swapFor: 'Swap for',
  numberTickets: number => `${number} tickets`,
  redeemed: 'Redeemed',
  won: 'Won',
  claimNow: 'Claim Now',
  claimed: 'Claimed'
};

export const commonStrings = {
  available: 'Available:',
  all: 'All',
  allTickets: 'All Tickets',
  cancel: 'Cancel',
  close: 'Close',
  done: 'Done',
  error: 'Error',
  // eslint-disable-next-line max-len
  noData:
    'There are currently no available prizes to play for in this category.  You can visit the Winner’s Circle to view prizes available for ticket redemption, or find more games in the game room.',
  noMachineData: 'There are currently no available machine to play for this name.',
  loading: 'Loading',
  next: 'Next',
  ok: 'Ok',
  skip: 'Skip',
  sortBy: 'Sort By',
  sortingCategory: 'Categories',
  sortingTicketCost: 'Ticket Cost',
  weeklyPlayStreak: (token, game) => `You have earned ${token} free tokens for playing ${game} games this week!`,
  dailyWinStreak: (token, game) => `You have earned ${token} free tokens for winning ${game} games today!`,
  day: 'Day',
  gotIt: 'Got it!',
  howToPlay: 'How to play!'
};

export const playHistoryStrings = {
  playHistory: 'Play History',
  freePlay: 'Free Play',
  tokens: 'Tokens',
  reportIssue: 'Report issue',
  reportedIssue: 'Reported',
  gameId: 'Game ID',
  videoShareMessage:
    // eslint-disable-next-line max-len
    'I’m playing real claw machines and winning real prizes on my phone. Check out these awesome games from Winner Winner. https://bit.ly/2WEi5bO'
};

export const shippingStrings = {
  city: 'City *',
  cityPlaceholder: 'E.G. New York',
  contactInformation: 'Contact information',
  email: 'Email *',
  emailPlaceholder: 'E.G. winner@winner.com',
  firstName: 'First name *',
  firstNamePlaceholder: 'E.G. John',
  fillOutForm: 'Fill out the form to ship your prize!',
  lastName: 'Last name *',
  lastNamePlaceholder: 'E.G. Smith',
  oopsCorrectErrors: 'Oops! Correct the errors',
  phone: 'Phone *',
  phonePlaceholder: '--- --- ----',
  shipping: 'Shipping',
  shippingAddress: 'Shipping address',
  state: 'State *',
  countries: 'Country *',
  countriesPlaceholder: 'E.G. UK',
  statePlaceholder: 'E.G. New York',
  streetAddress: 'Street address *',
  streetAddressPlaceholder: 'E.G. 1st Ave',
  streetAddress2: 'Street address 2',
  streetAddress2Placeholder: 'E.G. Apt #',
  submitShip: 'Submit and Ship',
  yourPrizeAwaits: 'Your prize awaits!',
  zipCode: 'Zip code *',
  zipCodePlaceholder: 'E.G. 90210',
  saveAddress: 'Save address',
  zipCodePlaceholderUK: 'E.G A9 9AA',
  zipCodePlaceholderCA: 'E.G A1A 1A1',
  zipCodePlaceholderAU: 'E.G 2618',
  phoneUKPlaceholder: ' E.G 44-----------',
  postalCode: 'Postal Code'
};
export const changeMyInfoStrings = {
  defaultShippingAddress: 'Default Shipping Address',
  city: 'City',
  cityPlaceholder: 'E.G. Queens',
  contactInformation: 'Contact information',
  email: 'Email',
  emailPlaceholder: 'E.G. winner@winner.com',
  firstName: 'First name',
  firstNamePlaceholder: 'E.G. John',
  fillOutForm: 'Fill out the form to ship your prize!',
  lastName: 'Last name',
  lastNamePlaceholder: 'E.G. Smith',
  oopsCorrectErrors: 'Oops! Correct the errors',
  phone: 'Phone',
  phonePlaceholder: '(---)--- ----',
  shipping: 'Shipping',
  shippingAddress: 'Shipping address',
  state: 'State',
  statePlaceholder: 'E.G. New York',
  streetAddress: 'Street address',
  streetAddressPlaceholder: 'E.G. 1st Ave',
  streetAddress2: 'Street address 2',
  streetAddress2Placeholder: 'E.G. Apt #',
  submitShip: 'Submit and ship',
  yourPrizeAwaits: 'Your prize awaits!',
  zipCode: 'Zip code',
  zipCodePlaceholder: 'E.G. 90210',
  saveAddress: 'Save address',
  birthday: 'Birthday',
  username: 'Username *',
  myCountry: 'My Country',
  save: 'Save',
  myInfo: 'My Info',
  backToProfile: 'Back To Profile',
  country: 'Country',
  countryPlaceholder: 'E.G. London',
  mycountryPlaceholder: 'E.G. USA',
  zipCodePlaceholderUK: 'E.G A9 9AA',
  postalCode: 'Postal Code'
};

export const stateStrings = {
  alabama: 'Alabama',
  alaska: 'Alaska',
  arizona: 'Arizona',
  arkansas: 'Arkansas',
  california: 'California',
  colorado: 'Colorado',
  connecticut: 'Connecticut',
  delaware: 'Delaware',
  florida: 'Florida',
  georgia: 'Georgia',
  guam: 'Guam',
  hawaii: 'Hawaii',
  idaho: 'Idaho',
  illinois: 'Illinois',
  indiana: 'Indiana',
  iowa: 'Iowa',
  kansas: 'Kansas',
  kentucky: 'Kentucky',
  louisiana: 'Louisiana',
  maine: 'Maine',
  maryland: 'Maryland',
  massachusetts: 'Massachusetts',
  michigan: 'Michigan',
  minnesota: 'Minnesota',
  mississippi: 'Mississippi',
  missouri: 'Missouri',
  montana: 'Montana',
  nebraska: 'Nebraska',
  nevada: 'Nevada',
  newHampshire: 'New Hampshire',
  newJersey: 'New Jersey',
  newMexico: 'New Mexico',
  newYork: 'New York',
  northCarolina: 'North Carolina',
  northDakota: 'North Dakota',
  ohio: 'Ohio',
  oklahoma: 'Oklahoma',
  oregon: 'Oregon',
  pennsylvania: 'Pennsylvania',
  puertoRico: 'Puerto Rico',
  rhodeIsland: 'Rhode Island',
  southCarolina: 'South Carolina',
  southDakota: 'South Dakota',
  tennessee: 'Tennessee',
  texas: 'Texas',
  utah: 'Utah',
  vermont: 'Vermont',
  virginia: 'Virginia',
  washington: 'Washington',
  westVirginia: 'West Virginia',
  wisconsin: 'Wisconsin',
  wyoming: 'Wyoming'
};

export const reportIssueStrings = {
  dateOfPlay: 'Date of Play',
  lose: 'lose',
  prizeName: 'Prize Name',
  playerName: 'Player Name',
  playerId: 'Player ID',
  status: 'Status',
  timeOfPlay: 'Time of Play',
  gamePlayVideo: 'Gameplay Video',
  gameRoundId: 'Game Round ID',
  subject: 'Report Issue',
  videoNotAvailable: 'Video Not Available',
  win: 'Win',
  machineId: 'Machine ID',
  tokensCost: 'Tokens Cost'
};

export const onboardingStrings = {
  becomeVip: 'Become a VIP',
  earnBetterPrizes: 'Earn bigger \nand better prizes',
  earnBetterPrizesForAndroid: 'Earn bigger and \nbetter rewards',
  exclusiveGames: 'Get access to \nexclusive games',
  exclusiveGamesForAndroid: 'Get access to \nexclusive rewards',
  findOutOffers: 'Turn on notifications to find out about new games, prizes and more!',
  findOutOffersForAndroid: 'Turn on notifications to find out \nabout new games prizes and more!',
  freeShipping: 'Get free shipping \non all prizes',
  freeShippingForAndroid: 'Get free shipping \non all rewards',
  getNews: 'Get news',
  notifyMe: 'Notify me',
  notification: 'Notifications',
  playRealGames: 'Watch others play while you wait',
  playRealGamesForAndroid: 'Use those tickets to redeem real rewards!',
  prizesEveryWin: 'Get a prize for every win, or convert to tickets and save up for a premium prize!',
  prizesEveryWinForAndroid: 'Play, win and save tickets to \nselect from thousands of different rewards!',
  watchWhileWaiting: 'Win real prizes, mailed direct to you',
  watchWhileWaitingForAndroid: 'Earn tickets as you pass levels & set new \nhigh scores',
  welcome: 'Welcome!',
  winRealPrizes: 'Win real prizes',
  winRealPrizesForAndroid: 'EARN REAL \nREWARDS',
  winRealPrizesMailedDirect: 'Play real, physical arcade games live streaming on your device',
  winRealPrizesMailedDirectForAndroid: 'Choose from many different games to play from the game room',
};

export const leaderboardStrings = {
  MyRank: 'My Rank',
  MyWin: 'My VIP Wins',
  // leaderboard: 'Leaderboard',
  // totalWins: wins => `Total wins: ${wins}`,
  player: 'Player',
  rank: 'Rank',
  wins: 'VIP Wins',
  all: 'all',
  monthly: 'monthly',
  weekly: 'weekly',
  daily: 'daily',
  lifetime: 'lifetime',
  thisMonth: 'this month',
  thisWeek: 'this week',
  today: 'today'
};

export const changeUserNameStrings = {
  changeUsername: 'Change Username',
  submit: 'Submit', 
  changeYourUsername: 'Change your username...',
  nameTaken: 'This name is already taken! Please try another',
  nickNameTooLong: 'Nickname must be less than 13 characters'
};
export const myWallet = {
  quickAdd: 'Quick Add',
  myTokens: 'My Tokens',
  scanqr: 'SCAN QR',
  mobilePay: 'MOBILE PAY COMING SOON',
  insufficientToken: 'You have insufficient tokens to generate QR code,',
  buyTokenPack: 'buy any token packs then generate QR.'
};
export const QrModalStrings = {
  useQr: 'Use QR Scanner to Play In Person',
  freePlay: freePlay => `You have ${freePlay} Free Play${freePlay !== 1 ? 's' : ''}`,
  locate: "Locate the QR scanner on the machine you'd like to play and scan the above QR code.",
  cancelButtonText: 'Cancel'
};

export const bouncingAnimation = {
  ticket: 'TICKETS',
  youWon: "YOU'VE WON"
};

export const deleteAccountStrings = {
  deleteAccount: 'Delete Account',
  iUnderstandDescription: 'Your account and all associated \n data will be deleted. This is a \n non-reversible action and \n cannot be undone.',
  iUnderstand: 'I understand',
  keepMyAccount: 'Nevermind, keep my account',
  confirmDescription1: 'Please type ',
  confirmDescription2: 'DELETE',
  confirmDescription3: ' in the \n field below to completely \n delete your profile.',
  note: 'This action cannot be undone.',
  confirm: 'Confirm',
  placeholder: 'Typing...',
  error: 'Incorrect text entered',
};
